
/**
 * Detailed Business-Centric Algerian Category Taxonomy (~200 Entries)
 * Organized by Store Type with granular, bilingual categories.
 */

export const CATEGORY_THEMES = [
  {
    id: 'women-fashion',
    name_ar: 'ملابس نسائية',
    name_fr: 'Mode Féminine',
    icon: 'woman-outline',
    categories: [
      { id: 'robes', name_ar: 'فساتين', name_fr: 'Robes', icon: 'woman-outline' },
      { id: 'abayas', name_ar: 'عبايات', name_fr: 'Abayas', icon: 'woman-outline' },
      { id: 'tuniques', name_ar: 'تونيكات', name_fr: 'Tuniques', icon: 'woman-outline' },
      { id: 'blouses', name_ar: 'بلوزات', name_fr: 'Blouses', icon: 'shirt-outline' },
      { id: 'chemises-femme', name_ar: 'قمصان نسائية', name_fr: 'Chemises Femme', icon: 'shirt-outline' },
      { id: 'jupes', name_ar: 'تنانير', name_fr: 'Jupes', icon: 'woman-outline' },
      { id: 'pantalons-femme', name_ar: 'سراويل نسائية', name_fr: 'Pantalons Femme', icon: 'body-outline' },
      { id: 'jeans-femme', name_ar: 'جينز نسائي', name_fr: 'Jeans Femme', icon: 'body-outline' },
      { id: 'ensembles-femme', name_ar: 'أطقم نسائية', name_fr: 'Ensembles Femme', icon: 'briefcase-outline' },
      { id: 'pyjamas-femme', name_ar: 'ملابس نوم', name_fr: 'Pyjamas Femme', icon: 'moon-outline' },
      { id: 'lingerie-femme', name_ar: 'ملابس داخلية', name_fr: 'Lingerie Femme', icon: 'heart-outline' },
      { id: 'sport-femme', name_ar: 'ملابس رياضية', name_fr: 'Sport Femme', icon: 'fitness-outline' },
      { id: 'hijabs', name_ar: 'حجابات', name_fr: 'Hijabs', icon: 'woman-outline' },
      { id: 'manteaux-femme', name_ar: 'معاطف نسائية', name_fr: 'Manteaux Femme', icon: 'snow-outline' },
      { id: 'vestes-femme', name_ar: 'سترات نسائية', name_fr: 'Vestes Femme', icon: 'shirt-outline' },
      { id: 'chaussures-femme', name_ar: 'أحذية نسائية', name_fr: 'Chaussures Femme', icon: 'walk-outline' },
      { id: 'sandales-femme', name_ar: 'صنادل نسائية', name_fr: 'Sandales Femme', icon: 'sunny-outline' },
      { id: 'sacs-femme', name_ar: 'حقائب نسائية', name_fr: 'Sacs Femme', icon: 'bag-handle-outline' },
      { id: 'bijoux-femme', name_ar: 'إكسسوارات نسائية', name_fr: 'Bijoux Femme', icon: 'diamond-outline' },
      { id: 'montres-femme', name_ar: 'ساعات نسائية', name_fr: 'Montres Femme', icon: 'watch-outline' },
    ]
  },
  {
    id: 'men-fashion',
    name_ar: 'ملابس رجالية',
    name_fr: 'Mode Masculine',
    icon: 'man-outline',
    categories: [
      { id: 'tshirts-homme', name_ar: 'تيشيرتات', name_fr: 'Tshirts Homme', icon: 'shirt-outline' },
      { id: 'chemises-homme', name_ar: 'قمصان رجالية', name_fr: 'Chemises Homme', icon: 'shirt-outline' },
      { id: 'pantalons-homme', name_ar: 'سراويل رجالية', name_fr: 'Pantalons Homme', icon: 'body-outline' },
      { id: 'jeans-homme', name_ar: 'جينز رجالي', name_fr: 'Jeans Homme', icon: 'body-outline' },
      { id: 'costumes', name_ar: 'بدلات', name_fr: 'Costumes', icon: 'briefcase-outline' },
      { id: 'vestes-homme', name_ar: 'سترات رجالية', name_fr: 'Vestes Homme', icon: 'shirt-outline' },
      { id: 'manteaux-homme', name_ar: 'معاطف رجالية', name_fr: 'Manteaux Homme', icon: 'snow-outline' },
      { id: 'sport-homme', name_ar: 'ملابس رياضية', name_fr: 'Sport Homme', icon: 'fitness-outline' },
      { id: 'sous-vetements', name_ar: 'ملابس داخلية', name_fr: 'SousVetements', icon: 'body-outline' },
      { id: 'pyjamas-homme', name_ar: 'ملابس نوم', name_fr: 'Pyjamas Homme', icon: 'moon-outline' },
      { id: 'chaussures-homme', name_ar: 'أحذية رجالية', name_fr: 'Chaussures Homme', icon: 'walk-outline' },
      { id: 'sandales-homme', name_ar: 'صنادل رجالية', name_fr: 'Sandales Homme', icon: 'sunny-outline' },
      { id: 'ceintures', name_ar: 'أحزمة', name_fr: 'Ceintures', icon: 'ellipse-outline' },
      { id: 'portefeuilles', name_ar: 'محافظ', name_fr: 'Portefeuilles', icon: 'wallet-outline' },
      { id: 'montres-homme', name_ar: 'ساعات رجالية', name_fr: 'Montres Homme', icon: 'watch-outline' },
      { id: 'lunettes-soleil', name_ar: 'نظارات شمسية', name_fr: 'Lunettes Soleil', icon: 'eye-outline' },
      { id: 'casquettes', name_ar: 'قبعات', name_fr: 'Casquettes', icon: 'baseball-outline' },
      { id: 'gants', name_ar: 'قفازات', name_fr: 'Gants', icon: 'hand-left-outline' },
      { id: 'echarpes', name_ar: 'أوشحة', name_fr: 'Echarpes', icon: 'snow-outline' },
      { id: 'sacs-dos', name_ar: 'حقائب ظهر', name_fr: 'Sacs Dos', icon: 'bag-handle-outline' },
    ]
  },
  {
    id: 'electronics',
    name_ar: 'إلكترونيات',
    name_fr: 'Électronique',
    icon: 'laptop-outline',
    categories: [
      { id: 'smartphones', name_ar: 'هواتف ذكية', name_fr: 'Smartphones', icon: 'phone-portrait-outline' },
      { id: 'accessoires-mobile', name_ar: 'ملحقات هواتف', name_fr: 'Accessoires Mobile', icon: 'flash-outline' },
      { id: 'tablettes', name_ar: 'أجهزة لوحية', name_fr: 'Tablettes', icon: 'tablet-portrait-outline' },
      { id: 'ordinateurs', name_ar: 'حواسيب', name_fr: 'Ordinateurs', icon: 'laptop-outline' },
      { id: 'ordinateurs-bureau', name_ar: 'حواسيب مكتبية', name_fr: 'Ordinateurs Bureau', icon: 'desktop-outline' },
      { id: 'ecrans', name_ar: 'شاشات', name_fr: 'Ecrans', icon: 'desktop-outline' },
      { id: 'claviers', name_ar: 'لوحات مفاتيح', name_fr: 'Claviers', icon: 'grid-outline' },
      { id: 'souris', name_ar: 'فأرات', name_fr: 'Souris', icon: 'navigate-outline' },
      { id: 'imprimantes', name_ar: 'طابعات', name_fr: 'Imprimantes', icon: 'print-outline' },
      { id: 'stockage', name_ar: 'وحدات تخزين', name_fr: 'Stockage', icon: 'server-outline' },
      { id: 'cle-usb', name_ar: 'ذاكرة USB', name_fr: 'Cle USB', icon: 'save-outline' },
      { id: 'cartes-memoire', name_ar: 'بطاقات ذاكرة', name_fr: 'Cartes Memoire', icon: 'save-outline' },
      { id: 'ecouteurs', name_ar: 'سماعات', name_fr: 'Ecouteurs', icon: 'headset-outline' },
      { id: 'haut-parleurs', name_ar: 'مكبرات صوت', name_fr: 'HautParleurs', icon: 'volume-high-outline' },
      { id: 'montres-connectees', name_ar: 'ساعات ذكية', name_fr: 'Montres Connectees', icon: 'watch-outline' },
      { id: 'televisions', name_ar: 'تلفزيونات', name_fr: 'Televisions', icon: 'tv-outline' },
      { id: 'recepteurs', name_ar: 'أجهزة استقبال', name_fr: 'Recepteurs', icon: 'tv-outline' },
      { id: 'cameras', name_ar: 'كاميرات', name_fr: 'Cameras', icon: 'camera-outline' },
      { id: 'surveillance', name_ar: 'كاميرات مراقبة', name_fr: 'Surveillance', icon: 'videocam-outline' },
      { id: 'routeurs', name_ar: 'أجهزة راوتر', name_fr: 'Routeurs', icon: 'wifi-outline' },
    ]
  },
  {
    id: 'home',
    name_ar: 'المنزل',
    name_fr: 'Maison',
    icon: 'home-outline',
    categories: [
      { id: 'meubles', name_ar: 'أثاث', name_fr: 'Meubles', icon: 'bed-outline' },
      { id: 'canapes', name_ar: 'أرائك', name_fr: 'Canapes', icon: 'home-outline' },
      { id: 'tables', name_ar: 'طاولات', name_fr: 'Tables', icon: 'home-outline' },
      { id: 'chaises', name_ar: 'كراسي', name_fr: 'Chaises', icon: 'home-outline' },
      { id: 'armoires', name_ar: 'خزائن', name_fr: 'Armoires', icon: 'home-outline' },
      { id: 'bibliotheques', name_ar: 'مكتبات', name_fr: 'Bibliotheques', icon: 'home-outline' },
      { id: 'tapis', name_ar: 'سجاد', name_fr: 'Tapis', icon: 'home-outline' },
      { id: 'rideaux', name_ar: 'ستائر', name_fr: 'Rideaux', icon: 'home-outline' },
      { id: 'coussins', name_ar: 'وسائد', name_fr: 'Coussins', icon: 'bed-outline' },
      { id: 'couvertures', name_ar: 'أغطية', name_fr: 'Couvertures', icon: 'bed-outline' },
      { id: 'eclairage', name_ar: 'إضاءة', name_fr: 'Eclairage', icon: 'bulb-outline' },
      { id: 'lampes', name_ar: 'مصابيح', name_fr: 'Lampes', icon: 'bulb-outline' },
      { id: 'decorations', name_ar: 'ديكورات', name_fr: 'Decorations', icon: 'prism-outline' },
      { id: 'miroirs', name_ar: 'مرايا', name_fr: 'Miroirs', icon: 'eye-outline' },
      { id: 'rangements', name_ar: 'تخزين', name_fr: 'Rangements', icon: 'cube-outline' },
      { id: 'nettoyage', name_ar: 'تنظيف', name_fr: 'Nettoyage', icon: 'water-outline' },
      { id: 'balais', name_ar: 'مكانس', name_fr: 'Balais', icon: 'brush-outline' },
      { id: 'poubelles', name_ar: 'سلال مهملات', name_fr: 'Poubelles', icon: 'trash-outline' },
      { id: 'sechoirs', name_ar: 'مجففات ملابس', name_fr: 'Sechoirs', icon: 'sunny-outline' },
      { id: 'etageres', name_ar: 'رفوف', name_fr: 'Etageres', icon: 'cube-outline' },
    ]
  },
  {
    id: 'kitchen',
    name_ar: 'المطبخ',
    name_fr: 'Cuisine',
    icon: 'restaurant-outline',
    categories: [
      { id: 'ustensiles', name_ar: 'أدوات مطبخ', name_fr: 'Ustensiles', icon: 'restaurant-outline' },
      { id: 'cuisson', name_ar: 'أواني طهي', name_fr: 'Cuisson', icon: 'flame-outline' },
      { id: 'casseroles', name_ar: 'قدور', name_fr: 'Casseroles', icon: 'restaurant-outline' },
      { id: 'poeles', name_ar: 'مقالي', name_fr: 'Poeles', icon: 'restaurant-outline' },
      { id: 'couteaux', name_ar: 'سكاكين', name_fr: 'Couteaux', icon: 'restaurant-outline' },
      { id: 'planches-coupe', name_ar: 'ألواح تقطيع', name_fr: 'Planches Coupe', icon: 'restaurant-outline' },
      { id: 'bols', name_ar: 'أوعية', name_fr: 'Bols', icon: 'restaurant-outline' },
      { id: 'assiettes', name_ar: 'أطباق', name_fr: 'Assiettes', icon: 'restaurant-outline' },
      { id: 'verres', name_ar: 'كؤوس', name_fr: 'Verres', icon: 'wine-outline' },
      { id: 'tasses', name_ar: 'أكواب', name_fr: 'Tasses', icon: 'cafe-outline' },
      { id: 'theieres', name_ar: 'أباريق شاي', name_fr: 'Theieres', icon: 'cafe-outline' },
      { id: 'cafetieres', name_ar: 'آلات قهوة', name_fr: 'Cafetieres', icon: 'cafe-outline' },
      { id: 'mixeurs', name_ar: 'خلاطات', name_fr: 'Mixeurs', icon: 'hardware-chip-outline' },
      { id: 'bouilloires', name_ar: 'غلايات', name_fr: 'Bouilloires', icon: 'water-outline' },
      { id: 'fours', name_ar: 'أفران', name_fr: 'Fours', icon: 'flame-outline' },
      { id: 'microondes', name_ar: 'ميكروويف', name_fr: 'Microondes', icon: 'restaurant-outline' },
      { id: 'refrigerateurs', name_ar: 'ثلاجات', name_fr: 'Refrigerateurs', icon: 'snow-outline' },
      { id: 'congelateurs', name_ar: 'مجمدات', name_fr: 'Congelateurs', icon: 'snow-outline' },
      { id: 'rangement-cuisine', name_ar: 'تخزين مطبخ', name_fr: 'Rangement Cuisine', icon: 'cube-outline' },
      { id: 'boites-aliments', name_ar: 'علب طعام', name_fr: 'Boites Aliments', icon: 'cube-outline' },
    ]
  },
  {
    id: 'beauty',
    name_ar: 'الجمال',
    name_fr: 'Beauté',
    icon: 'flask-outline',
    categories: [
      { id: 'maquillage', name_ar: 'مكياج', name_fr: 'Maquillage', icon: 'color-palette-outline' },
      { id: 'soins-peau', name_ar: 'عناية بالبشرة', name_fr: 'Soins Peau', icon: 'rose-outline' },
      { id: 'soins-cheveux', name_ar: 'عناية بالشعر', name_fr: 'Soins Cheveux', icon: 'water-outline' },
      { id: 'parfums', name_ar: 'عطور', name_fr: 'Parfums', icon: 'flask-outline' },
      { id: 'shampoings', name_ar: 'شامبو', name_fr: 'Shampoings', icon: 'water-outline' },
      { id: 'apres-shampoing', name_ar: 'بلسم', name_fr: 'ApresShampoing', icon: 'water-outline' },
      { id: 'creme-visage', name_ar: 'كريم وجه', name_fr: 'Creme Visage', icon: 'rose-outline' },
      { id: 'serums', name_ar: 'سيروم', name_fr: 'Serums', icon: 'water-outline' },
      { id: 'masques', name_ar: 'ماسكات', name_fr: 'Masques', icon: 'happy-outline' },
      { id: 'deodorants', name_ar: 'مزيل عرق', name_fr: 'Deodorants', icon: 'body-outline' },
      { id: 'rasage', name_ar: 'أدوات حلاقة', name_fr: 'Rasage', icon: 'cut-outline' },
      { id: 'epilation', name_ar: 'إزالة شعر', name_fr: 'Epilation', icon: 'cut-outline' },
      { id: 'vernis', name_ar: 'طلاء أظافر', name_fr: 'Vernis', icon: 'color-palette-outline' },
      { id: 'pinceaux', name_ar: 'فرش مكياج', name_fr: 'Pinceaux', icon: 'brush-outline' },
      { id: 'trousses', name_ar: 'حقائب تجميل', name_fr: 'Trousses', icon: 'bag-outline' },
      { id: 'savons', name_ar: 'صابون', name_fr: 'Savons', icon: 'water-outline' },
      { id: 'huiles', name_ar: 'زيوت', name_fr: 'Huiles', icon: 'flask-outline' },
      { id: 'soins-corps', name_ar: 'عناية بالجسم', name_fr: 'Soins Corps', icon: 'body-outline' },
      { id: 'soins-homme', name_ar: 'عناية رجالية', name_fr: 'Soins Homme', icon: 'man-outline' },
      { id: 'accessoires-beaute', name_ar: 'أدوات تجميل', name_fr: 'Accessoires Beaute', icon: 'brush-outline' },
    ]
  },
  {
    id: 'kids',
    name_ar: 'الأطفال',
    name_fr: 'Bébé & Enfants',
    icon: 'happy-outline',
    categories: [
      { id: 'vetements-enfants', name_ar: 'ملابس أطفال', name_fr: 'Vetements Enfants', icon: 'happy-outline' },
      { id: 'chaussures-enfants', name_ar: 'أحذية أطفال', name_fr: 'Chaussures Enfants', icon: 'walk-outline' },
      { id: 'jouets', name_ar: 'ألعاب', name_fr: 'Jouets', icon: 'happy-outline' },
      { id: 'jouets-educatifs', name_ar: 'ألعاب تعليمية', name_fr: 'Jouets Educatifs', icon: 'school-outline' },
      { id: 'poussettes', name_ar: 'عربات أطفال', name_fr: 'Poussettes', icon: 'happy-outline' },
      { id: 'lits-bebe', name_ar: 'أسرة أطفال', name_fr: 'Lits Bebe', icon: 'bed-outline' },
      { id: 'couches', name_ar: 'حفاظات', name_fr: 'Couches', icon: 'happy-outline' },
      { id: 'biberons', name_ar: 'رضاعات', name_fr: 'Biberons', icon: 'water-outline' },
      { id: 'lingettes', name_ar: 'مناديل مبللة', name_fr: 'Lingettes', icon: 'water-outline' },
      { id: 'sacs-ecole', name_ar: 'حقائب مدرسية', name_fr: 'Sacs Ecole', icon: 'school-outline' },
    ]
  },
  {
    id: 'automotive',
    name_ar: 'السيارات',
    name_fr: 'Automobile',
    icon: 'car-outline',
    categories: [
      { id: 'pieces-auto', name_ar: 'قطع غيار', name_fr: 'Pieces Auto', icon: 'car-outline' },
      { id: 'huiles-moteur', name_ar: 'زيوت محرك', name_fr: 'Huiles Moteur', icon: 'flask-outline' },
      { id: 'batteries', name_ar: 'بطاريات', name_fr: 'Batteries', icon: 'battery-charging-outline' },
      { id: 'pneus', name_ar: 'إطارات', name_fr: 'Pneus', icon: 'car-outline' },
      { id: 'accessoires-auto', name_ar: 'إكسسوارات سيارات', name_fr: 'Accessoires Auto', icon: 'car-outline' },
      { id: 'nettoyage-auto', name_ar: 'تنظيف سيارات', name_fr: 'Nettoyage Auto', icon: 'water-outline' },
      { id: 'audio-auto', name_ar: 'صوتيات سيارات', name_fr: 'Audio Auto', icon: 'volume-high-outline' },
      { id: 'gps', name_ar: 'أجهزة ملاحة', name_fr: 'GPS', icon: 'navigate-outline' },
      { id: 'cam-dash', name_ar: 'كاميرات سيارة', name_fr: 'Cam Dash', icon: 'videocam-outline' },
      { id: 'outils-auto', name_ar: 'أدوات سيارات', name_fr: 'Outils Auto', icon: 'construct-outline' },
    ]
  },
  {
    id: 'sports',
    name_ar: 'الرياضة',
    name_fr: 'Sports & Loisirs',
    icon: 'fitness-outline',
    categories: [
      { id: 'equipements-sport', name_ar: 'معدات رياضية', name_fr: 'Equipements Sport', icon: 'fitness-outline' },
      { id: 'vetements-sport', name_ar: 'ملابس رياضية', name_fr: 'Vetements Sport', icon: 'fitness-outline' },
      { id: 'chaussures-sport', name_ar: 'أحذية رياضية', name_fr: 'Chaussures Sport', icon: 'walk-outline' },
      { id: 'musculation', name_ar: 'كمال أجسام', name_fr: 'Musculation', icon: 'fitness-outline' },
      { id: 'fitness', name_ar: 'لياقة بدنية', name_fr: 'Fitness', icon: 'fitness-outline' },
      { id: 'camping', name_ar: 'تخييم', name_fr: 'Camping', icon: 'camera-outline' },
      { id: 'cyclisme', name_ar: 'دراجات', name_fr: 'Cyclisme', icon: 'bicycle-outline' },
      { id: 'natation', name_ar: 'سباحة', name_fr: 'Natation', icon: 'water-outline' },
      { id: 'football', name_ar: 'كرة قدم', name_fr: 'Football', icon: 'football-outline' },
      { id: 'tennis', name_ar: 'تنس', name_fr: 'Tennis', icon: 'tennisball-outline' },
    ]
  },
  {
    id: 'food',
    name_ar: 'الغذاء',
    name_fr: 'Alimentation',
    icon: 'basket-outline',
    categories: [
      { id: 'produits-alimentaires', name_ar: 'مواد غذائية', name_fr: 'Produits Alimentaires', icon: 'restaurant-outline' },
      { id: 'produits-locaux', name_ar: 'منتجات محلية', name_fr: 'Produits Locaux', icon: 'leaf-outline' },
      { id: 'epices', name_ar: 'توابل', name_fr: 'Epices', icon: 'restaurant-outline' },
      { id: 'huiles-alimentaires', name_ar: 'زيوت غذائية', name_fr: 'Huiles Alimentaires', icon: 'flask-outline' },
      { id: 'miel', name_ar: 'عسل', name_fr: 'Miel', icon: 'nutrition-outline' },
      { id: 'dattes', name_ar: 'تمور', name_fr: 'Dattes', icon: 'nutrition-outline' },
      { id: 'fruits-secs', name_ar: 'فواكه مجففة', name_fr: 'Fruits Secs', icon: 'nutrition-outline' },
      { id: 'confiseries', name_ar: 'حلويات', name_fr: 'Confiseries', icon: 'nutrition-outline' },
      { id: 'boissons', name_ar: 'مشروبات', name_fr: 'Boissons', icon: 'wine-outline' },
      { id: 'cafe-the', name_ar: 'قهوة وشاي', name_fr: 'Cafe The', icon: 'cafe-outline' },
    ]
  }
];

export const PRESET_CATEGORIES = CATEGORY_THEMES.flatMap(t => t.categories);
